
following error occured at Sun Mar 11 2018 17:36:47 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:36:56 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'tr' in 'field list'"
following error occured at Sun Mar 11 2018 17:36:57 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'tr' in 'field list'"
following error occured at Sun Mar 11 2018 17:36:59 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'tr' in 'field list'"
following error occured at Sun Mar 11 2018 17:38:02 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:40:50 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:42:34 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:43:13 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:43:21 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:44:17 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:52:29 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"
following error occured at Sun Mar 11 2018 17:53:07 GMT+0200 (שעון רגיל ירושלים) : "called by customerAPI.getDuplicateCustomer => called by customerController.getDuplicateCustomer => called by customerBL.getDuplicateCustomer => error in dal => Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''undefined')' at line 1"
following error occured at Mon Mar 12 2018 01:06:28 GMT+0200 (Jerusalem Standard Time) : {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
following error occured at Mon Mar 12 2018 01:06:28 GMT+0200 (Jerusalem Standard Time) : "called by storeAPI.getStatistics => called by storeController.getStatistics => called by storeBL.getStatistics => error in dal => Error: connect ECONNREFUSED 127.0.0.1:3306"
following error occured at Mon Mar 12 2018 01:06:28 GMT+0200 (Jerusalem Standard Time) : "called by storeAPI.getStatistics => called by storeController.getStatistics => unable to retrive statistics - please contact support center"
following error occured at Mon Mar 12 2018 03:40:01 GMT+0200 (Jerusalem Standard Time) : "called by cartAPI.addCart => called by cartController.addCart => called by cartBL.addCart error in dal => Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'"